name: Publish

# When a pull request is opened or updated the job will run the validation
# steps from the shared ecosystem workflow. This checks package versioning,
# changelog entries, and other publishability requirements. When you push a
# package tag, the shared workflow will attempt to publish that package.
on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened
      - labeled
      - unlabeled
  push:
    tags:
      - 'v*.*.*'
      - '*-v*.*.*'
  workflow_dispatch:

jobs:
  publish:
    uses: dart-lang/ecosystem/.github/workflows/publish.yaml@main
    permissions:
      contents: read
      id-token: write
      pull-requests: write
